# Generated by Django 2.2.4 on 2019-08-24 12:27

import core.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('photo', models.ImageField(upload_to=core.models.crop_image_save_loc)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('job', models.CharField(choices=[('student', 'Student'), ('govt', 'Government')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96)),
                ('language', models.CharField(default='en', max_length=10)),
                ('state', models.CharField(max_length=32)),
                ('district', models.CharField(max_length=32)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('level', models.IntegerField(default=0)),
                ('land_area', models.IntegerField(default=0, verbose_name='in hectares')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerCropYield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yield_potential', models.IntegerField(default=0, verbose_name='in kg')),
                ('yield_effective', models.IntegerField(verbose_name='in kg')),
                ('yield_wastage', models.IntegerField(default=0, verbose_name='in kg')),
                ('cultivated_area', models.IntegerField(verbose_name='in hectares')),
                ('pesticides_used', models.IntegerField(default=0, verbose_name='in kg')),
                ('investment', models.IntegerField(verbose_name='in Rs.')),
                ('profit', models.IntegerField(verbose_name='in Rs.')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yields', related_query_name='yield', to='core.Crop')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', related_query_name='crop', to='core.Farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('photo', models.ImageField(upload_to=core.models.equipment_image_save_loc)),
                ('rental_price', models.IntegerField(default=0, verbose_name='in Rs.')),
                ('rental_days', models.IntegerField(default=0)),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField(null=True)),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Tractor'), (2, 'Storage')])),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Farmer')),
            ],
        ),
    ]
