# Generated by Django 2.2.4 on 2019-08-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='rental_price',
            field=models.IntegerField(default=0, help_text='in Rs.'),
        ),
        migrations.AlterField(
            model_name='farmercropyield',
            name='cultivated_area',
            field=models.IntegerField(help_text='in hectares'),
        ),
        migrations.AlterField(
            model_name='farmercropyield',
            name='investment',
            field=models.IntegerField(help_text='in Rs.'),
        ),
        migrations.AlterField(
            model_name='farmercropyield',
            name='pesticides_used',
            field=models.IntegerField(default=0, help_text='in kg'),
        ),
        migrations.AlterField(
            model_name='farmercropyield',
            name='profit',
            field=models.IntegerField(help_text='in Rs.'),
        ),
        migrations.AlterField(
            model_name='farmercropyield',
            name='yield_effective',
            field=models.IntegerField(help_text='in kg'),
        ),
        migrations.AlterField(
            model_name='farmercropyield',
            name='yield_potential',
            field=models.IntegerField(default=0, help_text='in kg'),
        ),
        migrations.AlterField(
            model_name='farmercropyield',
            name='yield_wastage',
            field=models.IntegerField(default=0, help_text='in kg'),
        ),
    ]
