# Generated by Django 2.2.4 on 2019-08-24 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_expert_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.Chat')),
                ('farmer1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmerchat1', to='core.Farmer')),
                ('farmer2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmerchat2', to='core.Farmer')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.Chat')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Expert')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Farmer')),
            ],
        ),
    ]
