# Generated by Django 2.2.4 on 2019-08-25 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_farmercropyield_timestamp'),
        ('chat', '0002_client_message'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expertchat',
            unique_together={('farmer', 'expert')},
        ),
        migrations.AlterUniqueTogether(
            name='farmerchat',
            unique_together={('farmer1', 'farmer2')},
        ),
    ]
