EQUIPMENT_NONE = 0
EQUIPMENT_TRACTOR = 1
EQUIPMENT_STORAGE = 2

EQUIPMENT_TYPE_CHOICES = (
    (EQUIPMENT_NONE, 'None'),
    (EQUIPMENT_TRACTOR, 'Tractor'),
    (EQUIPMENT_STORAGE, 'Storage')
)

EQUIPMENT_TYPE_MAPS = {
    EQUIPMENT_NONE:'None',
    EQUIPMENT_TRACTOR:"Tractor",
    EQUIPMENT_STORAGE:"Storage",
}